####################
#   Your Profile   #
####################
title: your blog title
glad_text: your blog glad text
lang: ko
email: your-email@example.com
description: your description
twitter_username: your_twitter_username_without_@
github_username:  your_github_username_without_#
disqus:

show-about: true
about-title: Introduce My Self
about-description: this post contain resume
about-image: /assets/images/covers/telephone-pole.jpg

###############
#    build    #
###############
baseurl: ""
imageurl: "/assets/images"
url: ""
markdown: kramdown
plugins:
  - jekyll-seo-tag